hw2
ValeriyNiz/Node.js-HW-RestApi pull request #1
Opened 2023-01-02 18:30 UTC by ValeriyNiz

Проверьте пожалуйста

2023-01-02 18:35 UTC, KhYulian commented on helpers/createError.js
> +};
Краще використовувати класи class ServerError(or other name) extends Error {}

2023-01-02 18:36 UTC, KhYulian commented on models/index.js
> +/* eslint-disable no-useless-catch */
/* eslint-disable такого використовувати не потрібно. Або змініть правила еслінт, або, що краще, виправте помилку на яку вказує лінтер

2023-01-02 18:37 UTC, KhYulian commented on models/index.js
> +  }
особливої потреби у try catch в цих функціях немає - видаляйте

2023-01-02 18:37 UTC, KhYulian commented on routes/api/contacts.js
> +    const result = await contacts.listContacts();
Зробіть десруктуризацію contacts

2023-01-02 18:38 UTC, KhYulian commented on routes/api/contacts.js
> +    }
Валідацію винесіть в окрему middleware, яка спрацьовуватиме перед контроллером, аналогічно в інших місцях

2023-01-02 18:39 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-02 18:40 UTC, KhYulian commented
Також не забувайте відписувати на коменти по мірі виправлення

2023-01-02 18:50 UTC, ValeriyNiz commented on models/index.js
> +  }
удалил try catch из функций

2023-01-02 19:04 UTC, ValeriyNiz commented on models/index.js
> +/* eslint-disable no-useless-catch */
исправлена ошибка

2023-01-03 08:13 UTC, ValeriyNiz commented on routes/api/contacts.js
> +    const result = await contacts.listContacts();
сделана деструктуризация contacts

2023-01-03 11:44 UTC, ValeriyNiz commented on routes/api/contacts.js
> +    }
добавил middleware

2023-01-04 21:27 UTC, ValeriyNiz commented on helpers/createError.js
> +};
переделал на class

2023-01-05 08:06 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-05 08:06 UTC, merged